// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/ibc/core/client/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types1 "github.com/cosmos/cosmos-sdk/codec/types"
	types "github.com/cosmos/cosmos-sdk/x/upgrade/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgClientUpdate is request type for the Query/Params RPC method.
type MsgClientUpdate struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// the client identifier for the client to be updated if the proposal passes
	SubjectClientId string `protobuf:"bytes,2,opt,name=subject_client_id,json=subjectClientId,proto3" json:"subject_client_id,omitempty" yaml:"subject_client_id"`
	// the substitute client identifier for the client standing in for the subject
	// client
	SubstituteClientId string `protobuf:"bytes,3,opt,name=substitute_client_id,json=substituteClientId,proto3" json:"substitute_client_id,omitempty" yaml:"substitute_client_id"`
}

func (m *MsgClientUpdate) Reset()         { *m = MsgClientUpdate{} }
func (m *MsgClientUpdate) String() string { return proto.CompactTextString(m) }
func (*MsgClientUpdate) ProtoMessage()    {}
func (*MsgClientUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_d113edbb69925d40, []int{0}
}
func (m *MsgClientUpdate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClientUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClientUpdate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClientUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClientUpdate.Merge(m, src)
}
func (m *MsgClientUpdate) XXX_Size() int {
	return m.Size()
}
func (m *MsgClientUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClientUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClientUpdate proto.InternalMessageInfo

// MsgClientUpdateResponse is response type for the Query/Params RPC method.
type MsgClientUpdateResponse struct {
}

func (m *MsgClientUpdateResponse) Reset()         { *m = MsgClientUpdateResponse{} }
func (m *MsgClientUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClientUpdateResponse) ProtoMessage()    {}
func (*MsgClientUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d113edbb69925d40, []int{1}
}
func (m *MsgClientUpdateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClientUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClientUpdateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClientUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClientUpdateResponse.Merge(m, src)
}
func (m *MsgClientUpdateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClientUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClientUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClientUpdateResponse proto.InternalMessageInfo

// MsgUpgrade is request type for the Query/Params RPC method.
type MsgUpgrade struct {
	Authority string     `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Plan      types.Plan `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan"`
	// An UpgradedClientState must be provided to perform an IBC breaking upgrade.
	// This will make the chain commit to the correct upgraded (self) client state
	// before the upgrade occurs, so that connecting chains can verify that the
	// new upgraded client is valid by verifying a proof on the previous version
	// of the chain. This will allow IBC connections to persist smoothly across
	// planned chain upgrades
	UpgradedClientState *types1.Any `protobuf:"bytes,3,opt,name=upgraded_client_state,json=upgradedClientState,proto3" json:"upgraded_client_state,omitempty" yaml:"upgraded_client_state"`
}

func (m *MsgUpgrade) Reset()         { *m = MsgUpgrade{} }
func (m *MsgUpgrade) String() string { return proto.CompactTextString(m) }
func (*MsgUpgrade) ProtoMessage()    {}
func (*MsgUpgrade) Descriptor() ([]byte, []int) {
	return fileDescriptor_d113edbb69925d40, []int{2}
}
func (m *MsgUpgrade) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpgrade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpgrade.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpgrade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpgrade.Merge(m, src)
}
func (m *MsgUpgrade) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpgrade) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpgrade.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpgrade proto.InternalMessageInfo

func (m *MsgUpgrade) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpgrade) GetPlan() types.Plan {
	if m != nil {
		return m.Plan
	}
	return types.Plan{}
}

func (m *MsgUpgrade) GetUpgradedClientState() *types1.Any {
	if m != nil {
		return m.UpgradedClientState
	}
	return nil
}

// MsgUpgradeResponse is response type for the Query/Params RPC method.
type MsgUpgradeResponse struct {
}

func (m *MsgUpgradeResponse) Reset()         { *m = MsgUpgradeResponse{} }
func (m *MsgUpgradeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpgradeResponse) ProtoMessage()    {}
func (*MsgUpgradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d113edbb69925d40, []int{3}
}
func (m *MsgUpgradeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpgradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpgradeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpgradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpgradeResponse.Merge(m, src)
}
func (m *MsgUpgradeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpgradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpgradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpgradeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgClientUpdate)(nil), "paramauthority.ibc.core.client.v1.MsgClientUpdate")
	proto.RegisterType((*MsgClientUpdateResponse)(nil), "paramauthority.ibc.core.client.v1.MsgClientUpdateResponse")
	proto.RegisterType((*MsgUpgrade)(nil), "paramauthority.ibc.core.client.v1.MsgUpgrade")
	proto.RegisterType((*MsgUpgradeResponse)(nil), "paramauthority.ibc.core.client.v1.MsgUpgradeResponse")
}

func init() {
	proto.RegisterFile("cosmos/ibc/core/client/v1/tx.proto", fileDescriptor_d113edbb69925d40)
}

var fileDescriptor_d113edbb69925d40 = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x63, 0x1a, 0x81, 0x7a, 0x45, 0xaa, 0x38, 0x82, 0x48, 0x43, 0x64, 0x17, 0x4f, 0x08,
	0xa9, 0x77, 0x4a, 0x10, 0x0c, 0xd9, 0x08, 0x0b, 0x0c, 0x91, 0xc0, 0xd0, 0x85, 0x25, 0x3a, 0xdb,
	0xc7, 0xd5, 0x95, 0xe3, 0xb3, 0x7c, 0xcf, 0x56, 0xbd, 0x30, 0x33, 0xf2, 0x27, 0xf0, 0xe7, 0x74,
	0x42, 0x15, 0x13, 0x53, 0x84, 0x92, 0xff, 0x20, 0x03, 0x33, 0xca, 0x9d, 0xaf, 0xa1, 0x2d, 0x52,
	0xe9, 0xe6, 0xf7, 0xfc, 0x79, 0x3f, 0xbe, 0xdf, 0x67, 0x23, 0x3f, 0x92, 0x6a, 0x26, 0x15, 0x4d,
	0xc2, 0x88, 0x46, 0xb2, 0xe0, 0x34, 0x4a, 0x13, 0x9e, 0x01, 0xad, 0x06, 0x14, 0x4e, 0x48, 0x5e,
	0x48, 0x90, 0xf8, 0x71, 0xce, 0x0a, 0x36, 0x63, 0x25, 0x1c, 0xc9, 0x22, 0x81, 0x9a, 0x24, 0x61,
	0x44, 0xd6, 0x2c, 0x31, 0x2c, 0xa9, 0x06, 0xbd, 0x8e, 0x90, 0x42, 0x6a, 0x9a, 0xae, 0x9f, 0x4c,
	0x61, 0x6f, 0x4f, 0x48, 0x29, 0x52, 0x4e, 0x75, 0x14, 0x96, 0x9f, 0x28, 0xcb, 0xea, 0xe6, 0xd5,
	0x53, 0x33, 0x77, 0x6a, 0x6a, 0xca, 0x5c, 0x14, 0x2c, 0xe6, 0xb4, 0x1a, 0x84, 0x1c, 0xd8, 0xc0,
	0xc6, 0x86, 0xf5, 0x7f, 0x38, 0x68, 0x77, 0xa2, 0xc4, 0x2b, 0x3d, 0xed, 0x30, 0x8f, 0x19, 0x70,
	0xdc, 0x47, 0xdb, 0xe7, 0x0b, 0x75, 0x9d, 0x7d, 0xe7, 0xc9, 0x76, 0xb0, 0x49, 0xe0, 0xd7, 0xe8,
	0x9e, 0x2a, 0xc3, 0x63, 0x1e, 0xc1, 0xd4, 0xec, 0x38, 0x4d, 0xe2, 0xee, 0xad, 0x35, 0x35, 0xee,
	0xaf, 0xe6, 0x5e, 0xb7, 0x66, 0xb3, 0x74, 0xe4, 0x5f, 0x41, 0xfc, 0x60, 0xb7, 0xc9, 0x99, 0x59,
	0x6f, 0x62, 0xfc, 0x0e, 0x75, 0x54, 0x19, 0x2a, 0x48, 0xa0, 0x04, 0xfe, 0x57, 0xb3, 0x2d, 0xdd,
	0xcc, 0x5b, 0xcd, 0xbd, 0x47, 0xe7, 0xcd, 0xae, 0x50, 0x7e, 0x80, 0x37, 0x69, 0xdb, 0x72, 0xd4,
	0xfe, 0xf2, 0xcd, 0x6b, 0xf9, 0x7b, 0xe8, 0xe1, 0x25, 0x4d, 0x01, 0x57, 0xb9, 0xcc, 0x14, 0xf7,
	0xbf, 0x3b, 0x08, 0x4d, 0x94, 0x38, 0x34, 0x26, 0x5c, 0x23, 0xf5, 0x05, 0x6a, 0xe7, 0x29, 0xcb,
	0xb4, 0xba, 0x9d, 0x61, 0x9f, 0x18, 0x5f, 0x89, 0x75, 0xb0, 0x71, 0x94, 0xbc, 0x4d, 0x59, 0x36,
	0x6e, 0x9f, 0xce, 0xbd, 0x56, 0xa0, 0x79, 0x7c, 0x8c, 0x1e, 0x34, 0x4c, 0x6c, 0x17, 0x56, 0xc0,
	0x80, 0x6b, 0x65, 0x3b, 0xc3, 0x0e, 0x31, 0xb7, 0x23, 0xf6, 0x76, 0xe4, 0x65, 0x56, 0x8f, 0xf7,
	0x57, 0x73, 0xaf, 0x6f, 0xf4, 0xfe, 0xb3, 0xd8, 0x0f, 0xee, 0xdb, 0xbc, 0x51, 0xf6, 0x5e, 0x67,
	0x3b, 0x08, 0x6f, 0xf4, 0x58, 0x99, 0xc3, 0xdf, 0x0e, 0xda, 0x9a, 0x28, 0x81, 0x3f, 0xa3, 0xbb,
	0x17, 0x4e, 0x3b, 0x24, 0xd7, 0x7e, 0x6f, 0xe4, 0x92, 0x75, 0xbd, 0xd1, 0xcd, 0x6b, 0xec, 0x1e,
	0x58, 0xa2, 0x3b, 0xd6, 0xea, 0x83, 0xff, 0x6b, 0xd3, 0xe0, 0xbd, 0xe7, 0x37, 0xc2, 0xed, 0xc0,
	0xf1, 0x87, 0xd3, 0x85, 0xeb, 0x9c, 0x2d, 0x5c, 0xe7, 0xd7, 0xc2, 0x75, 0xbe, 0x2e, 0xdd, 0xd6,
	0xd9, 0xd2, 0x6d, 0xfd, 0x5c, 0xba, 0xad, 0x8f, 0x23, 0x91, 0xc0, 0x51, 0x19, 0x92, 0x48, 0xce,
	0xa8, 0x82, 0x82, 0x65, 0x82, 0xa7, 0xb2, 0xe2, 0x07, 0x15, 0xcf, 0xa0, 0x2c, 0xb8, 0xa2, 0x17,
	0xe7, 0xd1, 0x13, 0xfd, 0xdf, 0x42, 0x9d, 0x73, 0x15, 0xde, 0xd6, 0x97, 0x7a, 0xf6, 0x27, 0x00,
	0x00, 0xff, 0xff, 0x75, 0xc4, 0x17, 0xaf, 0xd2, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	ClientUpdate(ctx context.Context, in *MsgClientUpdate, opts ...grpc.CallOption) (*MsgClientUpdateResponse, error)
	Upgrade(ctx context.Context, in *MsgUpgrade, opts ...grpc.CallOption) (*MsgUpgradeResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ClientUpdate(ctx context.Context, in *MsgClientUpdate, opts ...grpc.CallOption) (*MsgClientUpdateResponse, error) {
	out := new(MsgClientUpdateResponse)
	err := c.cc.Invoke(ctx, "/paramauthority.ibc.core.client.v1.Msg/ClientUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Upgrade(ctx context.Context, in *MsgUpgrade, opts ...grpc.CallOption) (*MsgUpgradeResponse, error) {
	out := new(MsgUpgradeResponse)
	err := c.cc.Invoke(ctx, "/paramauthority.ibc.core.client.v1.Msg/Upgrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	ClientUpdate(context.Context, *MsgClientUpdate) (*MsgClientUpdateResponse, error)
	Upgrade(context.Context, *MsgUpgrade) (*MsgUpgradeResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ClientUpdate(ctx context.Context, req *MsgClientUpdate) (*MsgClientUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientUpdate not implemented")
}
func (*UnimplementedMsgServer) Upgrade(ctx context.Context, req *MsgUpgrade) (*MsgUpgradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upgrade not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ClientUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClientUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClientUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paramauthority.ibc.core.client.v1.Msg/ClientUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClientUpdate(ctx, req.(*MsgClientUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Upgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpgrade)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Upgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paramauthority.ibc.core.client.v1.Msg/Upgrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Upgrade(ctx, req.(*MsgUpgrade))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "paramauthority.ibc.core.client.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClientUpdate",
			Handler:    _Msg_ClientUpdate_Handler,
		},
		{
			MethodName: "Upgrade",
			Handler:    _Msg_Upgrade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/ibc/core/client/v1/tx.proto",
}

func (m *MsgClientUpdate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClientUpdate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClientUpdate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SubstituteClientId) > 0 {
		i -= len(m.SubstituteClientId)
		copy(dAtA[i:], m.SubstituteClientId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SubstituteClientId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SubjectClientId) > 0 {
		i -= len(m.SubjectClientId)
		copy(dAtA[i:], m.SubjectClientId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SubjectClientId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClientUpdateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClientUpdateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClientUpdateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpgrade) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpgrade) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpgrade) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpgradedClientState != nil {
		{
			size, err := m.UpgradedClientState.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.Plan.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpgradeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpgradeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpgradeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgClientUpdate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SubjectClientId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SubstituteClientId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClientUpdateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpgrade) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Plan.Size()
	n += 1 + l + sovTx(uint64(l))
	if m.UpgradedClientState != nil {
		l = m.UpgradedClientState.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpgradeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgClientUpdate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClientUpdate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClientUpdate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubjectClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubjectClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubstituteClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubstituteClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClientUpdateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClientUpdateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClientUpdateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpgrade) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpgrade: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpgrade: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Plan", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Plan.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpgradedClientState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpgradedClientState == nil {
				m.UpgradedClientState = &types1.Any{}
			}
			if err := m.UpgradedClientState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpgradeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpgradeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpgradeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
